// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sndtakeoklqreujrxrle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZHRha2Vva2xxcmV1anJ4cmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMDA2MzUsImV4cCI6MjA3NDg3NjYzNX0.-zzER8A2GC94Tf6w9Z7_0n9UGFpPpMwoOeHVUg3PJxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});